name: sentiment-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn=1.7.2
  - pandas
  - numpy
  - pip
  - ipykernel
  - setuptools 
  - wheel 
  - poppler 
  - transformers=4.35.2
  - pip:
      - fastapi==0.115.6
      - mlflow==2.18.0
      - joblib
      - uvicorn==0.24.0




